### ISSUE TITLE
Getting RelatedObjectDoesNotExist, Site has no siteconfiguration upon trying to access admin

### ISSUE THREAD

**Issue by Silidrone** [overhangio/tutor-credentials#26]
Using tutor version 16.1.7 with dev environment, following the README on this repo, I am getting an error after trying to access http://credentials.local.overhang.io:8150/admin

```
Environment:
Request Method: GET
Request URL: http://credentials.local.overhang.io:8150/admin/login/?next=/admin/

Django Version: 3.2.21
Python Version: 3.8.15
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'corsheaders',
 'csrf.apps.CsrfAppConfig',
 'release_util',
 'rest_framework',
 'rest_framework_jwt',
 'social_django',
 'sortedm2m',
 'statici18n',
 'waffle',
 'storages',
 'webpack_loader',
 'django_filters',
 'django_sites_extensions',
 'edx_credentials_themes',
 'drf_yasg',
 'hijack',
 'xss_utils',
 'credentials.apps.core',
 'credentials.apps.api',
 'credentials.apps.catalog',
 'credentials.apps.credentials',
 'credentials.apps.edx_django_extensions',
 'credentials.apps.credentials_theme_openedx',
 'credentials.apps.records',
 'credentials.apps.plugins',
 'credentials.apps.verifiable_credentials',
 'credentials.apps.edx_credentials_extensions']
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'edx_django_utils.cache.middleware.RequestCacheMiddleware',
 'edx_django_utils.monitoring.DeploymentMonitoringMiddleware',
 'edx_django_utils.monitoring.CookieMonitoringMiddleware',
 'edx_django_utils.monitoring.CachedCustomMonitoringMiddleware',
 'edx_django_utils.monitoring.MonitoringMemoryMiddleware',
 'edx_rest_framework_extensions.auth.jwt.middleware.JwtAuthCookieMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.sites.middleware.CurrentSiteMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'waffle.middleware.WaffleMiddleware',
 'ratelimit.middleware.RatelimitMiddleware',
 'edx_django_utils.cache.middleware.TieredCacheMiddleware',
 'edx_rest_framework_extensions.middleware.RequestMetricsMiddleware',
 'edx_rest_framework_extensions.auth.jwt.middleware.EnsureJWTAuthSettingsMiddleware',
 'crum.CurrentRequestUserMiddleware')



Traceback (most recent call last):
  File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/openedx/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/openedx/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/openedx/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/opt/pyenv/versions/3.8.15/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/openedx/venv/lib/python3.8/site-packages/django/template/context.py", line 244, in bind_template
    updates.update(processor(self.request))
  File "/openedx/credentials/credentials/apps/core/context_processors.py", line 12, in core
    "platform_name": site.siteconfiguration.platform_name,
  File "/openedx/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 421, in __get__
    raise self.RelatedObjectDoesNotExist(

Exception Type: RelatedObjectDoesNotExist at /admin/login/
Exception Value: Site has no siteconfiguration.

```

I have a siteconfiguration on my lms admin but I guess the credentials container doesnt see it? Also, there is an unapplied credentials-extensions migration that doesnt run even after tutor dev launch. I also tried to apply it but nothing changed, I am still getting the error.

**Comment by regisb** [comment]
Did you run `tutor dev launch`?

**Comment by Faraz32123** [comment]
Hi @Silidrone, what version of tutor-credentials plugin are you using?? Please use the latest.
Can u try accessing the admin panel after restarting the credentials service.

**Comment by Faraz32123** [comment]
Hi @Silidrone, do you have any progress?

**Comment by regisb** [comment]
> I'll work on that this week and if I make no progress perhaps I can open another issue

Please don't :) you shouldn't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
