### ISSUE TITLE
 ValueError: Missing staticfiles manifest entry for 'bundles/base.style-ltr-e90e766b6d9a62893e1a.css'

### ISSUE THREAD

**Issue by hinakhadim** [overhangio/tutor-credentials#3]
Upon setting fresh credentials service, I was getting this staticfiles manifest entry error: 

#### How to reproduce
1. Install credentials plugin and enable it and run `tutor config save`. [My discovery service is already enabled]
2. Then run `tutor local launch`
3. All services started and credentials service also started
4. Access `credentials.local.overhang.io` in browser. The browser didn't show anything. And the below error would generate in `credetials container logs`

```
2023-10-10 12:32:03 During handling of the above exception, another exception occurred:
2023-10-10 12:32:03 
2023-10-10 12:32:03 Traceback (most recent call last):
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
2023-10-10 12:32:03     response = self.get_response(request)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 130, in get_response
2023-10-10 12:32:03     response = self._middleware_chain(request)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
2023-10-10 12:32:03     response = response_for_exception(request, exc)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
2023-10-10 12:32:03     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 153, in handle_uncaught_exception
2023-10-10 12:32:03     return callback(request)
2023-10-10 12:32:03   File "/openedx/credentials/./credentials/apps/core/views.py", line 130, in render_500
2023-10-10 12:32:03     return render(request, template_name, status=500)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
2023-10-10 12:32:03     content = loader.render_to_string(template_name, context, request, using=using)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
2023-10-10 12:32:03     return template.render(context, request)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
2023-10-10 12:32:03     return self.template.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
2023-10-10 12:32:03     return self._render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
2023-10-10 12:32:03     return self.nodelist.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
2023-10-10 12:32:03     bit = node.render_annotated(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
2023-10-10 12:32:03     return self.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
2023-10-10 12:32:03     return compiled_parent._render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
2023-10-10 12:32:03     return self.nodelist.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
2023-10-10 12:32:03     bit = node.render_annotated(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
2023-10-10 12:32:03     return self.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 519, in render
2023-10-10 12:32:03     return self.nodelist.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
2023-10-10 12:32:03     bit = node.render_annotated(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
2023-10-10 12:32:03     return self.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/templatetags/i18n.py", line 194, in render
2023-10-10 12:32:03     output = self.nodelist.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
2023-10-10 12:32:03     bit = node.render_annotated(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
2023-10-10 12:32:03     return self.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
2023-10-10 12:32:03     return nodelist.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
2023-10-10 12:32:03     bit = node.render_annotated(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
2023-10-10 12:32:03     return self.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
2023-10-10 12:32:03     return template.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 172, in render
2023-10-10 12:32:03     return self._render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
2023-10-10 12:32:03     return self.nodelist.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
2023-10-10 12:32:03     bit = node.render_annotated(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
2023-10-10 12:32:03     return self.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
2023-10-10 12:32:03     result = self.nodelist.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
2023-10-10 12:32:03     bit = node.render_annotated(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
2023-10-10 12:32:03     return self.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
2023-10-10 12:32:03     return nodelist.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
2023-10-10 12:32:03     bit = node.render_annotated(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
2023-10-10 12:32:03     return self.render(context)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/template/library.py", line 192, in render
2023-10-10 12:32:03     output = self.func(*resolved_args, **resolved_kwargs)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/webpack_loader/templatetags/webpack_loader.py", line 22, in render_bundle
2023-10-10 12:32:03     tags = utils.get_as_tags(
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/webpack_loader/utils.py", line 74, in get_as_tags
2023-10-10 12:32:03     for chunk in bundle:
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/webpack_loader/utils.py", line 41, in _filter_by_extension
2023-10-10 12:32:03     for chunk in bundle:
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/webpack_loader/loader.py", line 72, in map_chunk_files_to_url
2023-10-10 12:32:03     url = self.get_chunk_url(files[chunk])
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/webpack_loader/loader.py", line 88, in get_chunk_url
2023-10-10 12:32:03     return staticfiles_storage.url(relpath)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 147, in url
2023-10-10 12:32:03     return self._url(self.stored_name, name, force)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 126, in _url
2023-10-10 12:32:03     hashed_name = hashed_name_func(*args)
2023-10-10 12:32:03   File "/openedx/venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 417, in stored_name
2023-10-10 12:32:03     raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
2023-10-10 12:32:03 ValueError: Missing staticfiles manifest entry for 'bundles/base.style-ltr-e90e766b6d9a62893e1a.css'
2023-10-10 12:32:03 [pid: 7|app: 0|req: 1/2] 172.19.0.5 () {44 vars in 1876 bytes} [Tue Oct 10 07:32:02 2023] GET / => generated 0 bytes in 643 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

**Comment by regisb** [comment]
> In the credentials/credentials/urls.py file, comment the line `urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)`.

1. Why does this change resolve the issue? What is the root cause of the issue in the first place?
2. What's the URL that is causing the 500 error?

**Comment by regisb** [comment]
> In the credentials/credentials/urls.py file, comment the line `urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)`.

Why does this change resolve the issue? What is the root cause of the issue in the first place?

**Comment by hinakhadim** [comment]
1. I didn't get the reason completely. but according to [this answer](https://stackoverflow.com/a/50010895), I thought it is creating some circular dependency and I should remove it.
2. I accessed two urls: first is `credentials.local.overhang.io` and second is to view the program certificate from django admin by clicking on `View on Site button`: `http://credentials.local.overhang.io/credentials/example/20a358a0f5734218850b5b64b276f401/`

<img width="1429" alt="image" src="https://github.com/overhangio/tutor-credentials/assets/112946189/61051bcf-d89c-4742-a1a8-cb9ac7a12e43">

**Comment by hinakhadim** [comment]
Hi, I debugged it and found the below root cause of the error. 
In credentials, there are two folder `static` and `assets`. In `static`, we put our static files which later collected into `assets` folder on running the `python manage.py collectstatic` command. The problem was that in [docker file ](https://github.com/overhangio/tutor-credentials/blob/main/tutorcredentials/templates/credentials/build/credentials/Dockerfile#L164-L165), First all static files collects into the `assets` folder. then `webpack` build the bundle and output it in `static` folder. So, our `bundle` folder remains only in `static` folder. And when we try to fetch the certificate, it loads files from `assets` folder and there our `bundle` folder don't exist because it exists in `static` folder only.

So the solution is that First command should be `node_modules/.bin/webpack --config webpack.config.js` and then run `ython3 manage.py collectstatic --noinput` in dockerfile.

**Comment by regisb** [comment]
Congratulations on finding the root cause @hinakhadim :bow: this kind of bug is very tricky to troubleshoot...
